services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: creative_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  engine:
    build:
      context: ../engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../engine/.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/creative_portal
    volumes:
      - engine_storage:/app/storage
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head || true &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  console:
    build:
      context: ../console
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - engine

volumes:
  postgres_data:
  engine_storage:
